"""TrialAI Bias Analysis Service v3.0 — Real fairness auditing."""

import os
import io
import uuid
import json
import subprocess
import traceback
import asyncio
import httpx
import google.generativeai as genai
from google.api_core.exceptions import ResourceExhausted
from pathlib import Path
from contextlib import asynccontextmanager

import numpy as np
import pandas as pd
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.utils.class_weight import compute_sample_weight
from dotenv import load_dotenv

from fastapi import FastAPI, UploadFile, File, Form
from fastapi.responses import Response, FileResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from utils import (
    load_model_file, prepare_dataset, compute_fairlearn_metrics,
    compute_shap_values, detect_proxy_features,
    analyze_code_with_llm, generate_mitigated_code,
    generate_fallback_training_script,
)

# Load environment
load_dotenv(Path(__file__).parent.parent / ".env.local")

import re as _re


def _parse_retry_delay(error: Exception) -> float:
    """Extract retry_delay seconds from a 429 error message. Default 5s."""
    err_str = str(error)
    # Look for patterns like "retry_delay { seconds: 30 }" or "retryDelay":"30s"
    m = _re.search(r'retry.?delay.*?(\d+)', err_str, _re.IGNORECASE)
    if m:
        return float(m.group(1))
    return 5.0


def generate_rule_based_fallback(
    script_content: str,
    dataset_path: str,
    target_column: str,
    sensitive_attrs: list,
    output_model_path: str,
    proxy_features: list = None,
) -> str:
    """Generate a mitigated training script WITHOUT any LLM call.
    Always succeeds. Injects class_weight='balanced', sample reweighting,
    and proxy feature removal directly in Python."""

    proxy_list = proxy_features or []
    proxy_drop_code = ""
    if proxy_list:
        proxy_names = [p["feature"] if isinstance(p, dict) else str(p) for p in proxy_list]
        proxy_drop_code = f"""
# -- Fairness: Remove proxy features correlated with sensitive attributes --
proxy_features = {proxy_names}
proxy_to_drop = [c for c in proxy_features if c in X.columns and c != target_column]
if proxy_to_drop:
    print(f"Dropping proxy features: {{proxy_to_drop}}")
    X = X.drop(columns=proxy_to_drop)
"""

    return f'''# ==============================================================================
# RULE-BASED BIAS-MITIGATED TRAINING SCRIPT
# Generated by TrialAI Fairness Engine (no LLM -- deterministic fallback)
#
# Mitigation techniques applied:
#   1. class_weight="balanced" to handle class imbalance
#   2. Sample reweighting via compute_sample_weight
#   3. Proxy feature removal for features correlated with sensitive attributes
#   4. Stratified train/test split on target variable
# ==============================================================================

import json
import warnings
import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.utils.class_weight import compute_sample_weight

warnings.filterwarnings("ignore")

target_column = "{target_column}"
dataset_path = r"{dataset_path}"
output_path = r"{output_model_path}"
sensitive_attributes = {sensitive_attrs}

try:
    # -- Load data --
    df = pd.read_csv(dataset_path)
    print(f"Loaded dataset: {{df.shape}}")

    # -- Handle missing values --
    for col in df.select_dtypes(include=["number"]).columns:
        df[col] = df[col].fillna(df[col].median())
    for col in df.select_dtypes(include=["object", "category"]).columns:
        df[col] = df[col].fillna(df[col].mode()[0] if not df[col].mode().empty else "UNKNOWN")

    # -- Encode categorical columns --
    label_encoders = {{}}
    for col in df.select_dtypes(include=["object", "category"]).columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        label_encoders[col] = le

    # -- Separate features and target --
    if target_column not in df.columns:
        raise ValueError(f"Target column '{{target_column}}' not found in dataset columns: {{list(df.columns)}}")

    y = df[target_column].values
    X = df.drop(columns=[target_column])
{proxy_drop_code}
    # -- Fairness: Compute balanced sample weights --
    sample_weights = compute_sample_weight("balanced", y)
    print(f"Features: {{X.shape[1]}}, Samples: {{X.shape[0]}}")

    # -- Stratified split --
    X_train, X_test, y_train, y_test, sw_train, sw_test = train_test_split(
        X, y, sample_weights, test_size=0.2, random_state=42, stratify=y
    )

    # -- Scale features --
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # -- Train with class_weight="balanced" --
    # Try multiple models and pick the best
    models = [
        ("LogisticRegression", LogisticRegression(
            class_weight="balanced", max_iter=1000, random_state=42
        )),
        ("RandomForest", RandomForestClassifier(
            class_weight="balanced", n_estimators=100, random_state=42
        )),
    ]

    best_model = None
    best_acc = 0.0
    best_name = ""

    for name, model in models:
        try:
            model.fit(X_train_scaled, y_train, sample_weight=sw_train)
            acc = accuracy_score(y_test, model.predict(X_test_scaled))
            print(f"  {{name}} accuracy: {{acc:.4f}}")
            if acc > best_acc:
                best_acc = acc
                best_model = model
                best_name = name
        except Exception as me:
            print(f"  {{name}} failed: {{me}}")

    if best_model is None:
        # Ultimate fallback - plain LogisticRegression without sample_weight
        best_model = LogisticRegression(max_iter=1000, random_state=42)
        best_model.fit(X_train_scaled, y_train)
        best_acc = accuracy_score(y_test, best_model.predict(X_test_scaled))
        best_name = "LogisticRegression-plain"

    print(f"Best model: {{best_name}} ({{best_acc:.4f}})")

    # -- Save model --
    joblib.dump(best_model, output_path)
    print(f"Model saved to: {{output_path}}")

    # -- Output JSON result --
    print(json.dumps({{"accuracy": round(best_acc, 4), "status": "success"}}))

except Exception as e:
    print(f"Error: {{e}}")
    print(json.dumps({{"accuracy": 0.0, "status": "error", "error": str(e)}}))
'''


class GeminiRotator:
    """Round-robin key manager with retry_delay-aware 429 handling."""

    MODEL_NAME = "gemini-2.0-flash"

    def __init__(self):
        self.keys = []
        if os.environ.get("GEMINI_API_KEY"):
            self.keys.append(os.environ.get("GEMINI_API_KEY"))
        for i in range(1, 13):
            k = os.environ.get(f"GEMINI_API_KEY_{i}") or os.environ.get(f"GOOGLE_API_KEY_{i}")
            if k and k not in self.keys:
                self.keys.append(k)
        self.idx = 0
        print(f"[GeminiRotator] Loaded {len(self.keys)} API keys")

    def get_next_key(self):
        if not self.keys:
            return ""
        k = self.keys[self.idx]
        self.idx = (self.idx + 1) % len(self.keys)
        return k

    def _get_n_keys(self, n: int) -> list:
        """Get n distinct keys for parallel use."""
        n = min(n, len(self.keys))
        keys = []
        for _ in range(n):
            keys.append(self.get_next_key())
        return keys

    async def _call_with_key(self, prompt: str, api_key: str) -> str:
        """Single LLM call using direct HTTP REST API (no deprecated SDK)."""
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.MODEL_NAME}:generateContent"
        body = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.3, "maxOutputTokens": 8192},
        }
        async with httpx.AsyncClient(timeout=90) as client:
            resp = await client.post(url, json=body, params={"key": api_key})
            resp.raise_for_status()
            data = resp.json()
            return data["candidates"][0]["content"]["parts"][0]["text"]

    def _is_rate_limit(self, e: Exception) -> bool:
        err_str = str(e).lower()
        return "429" in err_str or "resourceexhausted" in err_str or "quota" in err_str

    def _is_model_not_found(self, e: Exception) -> bool:
        err_str = str(e).lower()
        return "404" in err_str or "not found" in err_str or "not supported" in err_str

    # ── Sequential with retry_delay: try each key, wait the server-specified delay on 429 ──
    async def generate_content(self, prompt: str, fan_out: int = 4) -> str:
        """Try keys with fan-out. On 429, wait the retry_delay before next key."""
        if not self.keys:
            raise ValueError("No Gemini keys found in environment.")

        fan_out = min(fan_out, len(self.keys))
        keys_to_use = self._get_n_keys(fan_out)

        # Create tasks for each key
        async def _try_key(key: str, idx: int) -> str:
            try:
                result = await self._call_with_key(prompt, key)
                print(f"[GeminiRotator] Key slot {idx} responded ✓")
                return result
            except Exception as e:
                if self._is_rate_limit(e):
                    delay = _parse_retry_delay(e)
                    print(f"[GeminiRotator] Key slot {idx} hit 429, retry_delay={delay}s")
                    await asyncio.sleep(delay)
                raise

        # Race all keys — return the first successful result
        tasks = [asyncio.create_task(_try_key(k, i)) for i, k in enumerate(keys_to_use)]
        pending = set(tasks)
        last_err = None

        while pending:
            finished, pending = await asyncio.wait(pending, return_when=asyncio.FIRST_COMPLETED)
            for task in finished:
                try:
                    result = task.result()
                    for p in pending:
                        p.cancel()
                    return result
                except Exception as e:
                    last_err = e
                    continue

        # All fan-out failed — sequential retry on remaining keys with delay
        print(f"[GeminiRotator] All {fan_out} parallel calls failed. Sequential retry with delay...")
        for key in self.keys:
            if key not in keys_to_use:
                try:
                    return await self._call_with_key(prompt, key)
                except Exception as e:
                    if self._is_rate_limit(e):
                        delay = _parse_retry_delay(e)
                        print(f"[GeminiRotator] Sequential key hit 429, waiting {delay}s...")
                        await asyncio.sleep(delay)
                    last_err = e
                    continue

        raise Exception(f"All keys exhausted. Last error: {last_err}")

    # ── Parallel multi-task: run DIFFERENT prompts on DIFFERENT keys simultaneously ──
    async def generate_parallel_tasks(self, prompts: list[str]) -> list[str]:
        """Run N different prompts across N different keys concurrently.
        Returns a list of results in the same order as prompts."""
        if not self.keys:
            raise ValueError("No Gemini keys found in environment.")

        n = len(prompts)
        keys = self._get_n_keys(n)

        async def _run_task(prompt: str, key: str, idx: int) -> tuple[int, str]:
            try:
                result = await self._call_with_key(prompt, key)
                print(f"[GeminiRotator] Task {idx} completed ✓")
                return (idx, result)
            except Exception as e:
                if self._is_rate_limit(e):
                    delay = _parse_retry_delay(e)
                    print(f"[GeminiRotator] Task {idx} hit 429, waiting {delay}s before fallback")
                    await asyncio.sleep(delay)
                # Retry with remaining keys
                for fallback_key in self.keys:
                    if fallback_key != key:
                        try:
                            result = await self._call_with_key(prompt, fallback_key)
                            print(f"[GeminiRotator] Task {idx} completed on fallback ✓")
                            return (idx, result)
                        except Exception as fe:
                            if self._is_rate_limit(fe):
                                delay = _parse_retry_delay(fe)
                                await asyncio.sleep(delay)
                            continue
                raise Exception(f"Task {idx} failed on all keys")

        tasks = [_run_task(p, k, i) for i, (p, k) in enumerate(zip(prompts, keys))]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        output = [""] * n
        for r in results:
            if isinstance(r, Exception):
                raise r
            idx, text = r
            output[idx] = text
        return output

rotator = GeminiRotator()

def get_gemini_key():
    return rotator.get_next_key()

WORKSPACE_DIR = Path(__file__).parent / "workspaces"

# ─── Session Store ────────────────────────────────────────────────────────────
sessions: dict = {}


def save_session(session_id: str, session_data: dict) -> None:
    """Persist session data to disk as JSON for cross-restart durability."""
    workspace = Path(session_data.get("workspace", WORKSPACE_DIR / session_id))
    workspace.mkdir(parents=True, exist_ok=True)
    session_file = workspace / "session.json"
    # Write a JSON-safe copy (strip non-serializable fields)
    safe_data = {}
    for k, v in session_data.items():
        try:
            json.dumps(v)
            safe_data[k] = v
        except (TypeError, ValueError):
            safe_data[k] = str(v)
    session_file.write_text(json.dumps(safe_data, indent=2))


def load_session(session_id: str) -> dict | None:
    """Load session from memory, falling back to disk if not found."""
    if session_id in sessions:
        return sessions[session_id]
    # Try disk
    session_file = WORKSPACE_DIR / session_id / "session.json"
    if session_file.exists():
        try:
            data = json.loads(session_file.read_text())
            sessions[session_id] = data  # Re-hydrate into memory
            print(f"[SESSION {session_id}] Restored from disk")
            return data
        except Exception as e:
            print(f"[SESSION {session_id}] Failed to restore from disk: {e}")
    return None


# ─── Global State (COMPAS demo) ──────────────────────────────────────────────
model_state: dict = {}


# ─── Lifespan: Load COMPAS on startup ────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    WORKSPACE_DIR.mkdir(exist_ok=True)
    print("[STARTUP] Loading COMPAS dataset...")
    url = "https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv"

    try:
        df = pd.read_csv(url)
        keep_cols = ["age", "sex", "race", "priors_count", "days_b_screening_arrest",
                     "c_charge_degree", "two_year_recid", "decile_score"]
        df = df[keep_cols].dropna()
        raw_race = df["race"].copy()

        label_encoders = {}
        for col in ["sex", "race", "c_charge_degree"]:
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col])
            label_encoders[col] = le

        feature_cols = [c for c in df.columns if c != "two_year_recid"]
        X_raw = df[feature_cols].values
        y = df["two_year_recid"].values

        scaler = StandardScaler()
        X = scaler.fit_transform(X_raw)

        lr = LogisticRegression(max_iter=1000, random_state=42)
        lr.fit(X, y)
        accuracy = accuracy_score(y, lr.predict(X))
        print(f"[OK] COMPAS model trained. Accuracy: {accuracy:.4f}")

        model_state.update({
            "model": lr, "scaler": scaler, "df": df, "X": X, "y": y,
            "feature_cols": feature_cols, "label_encoders": label_encoders,
            "raw_race": raw_race, "accuracy": accuracy,
        })
    except Exception as e:
        print(f"[WARN] COMPAS load failed: {e}")

    yield
    model_state.clear()
    sessions.clear()


app = FastAPI(
    title="TrialAI Bias Analysis Service",
    version="3.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_credentials=True,
    allow_methods=["*"], allow_headers=["*"],
)


# ─── Request Models ──────────────────────────────────────────────────────────
class AnalyzeRequest(BaseModel):
    dataset_name: str

class MitigateRequest(BaseModel):
    dataset_name: str
    technique: str

class SimulateRequest(BaseModel):
    race: str
    age: int
    prior_arrests: int

class RetrainRequest(BaseModel):
    session_id: str


# ═══════════════════════════════════════════════════════════════════════════════
#  COMPAS DEMO ENDPOINTS (fixed with real Fairlearn)
# ═══════════════════════════════════════════════════════════════════════════════

@app.get("/health")
async def health_check():
    return {"status": "ok"}


@app.post("/analyze")
async def analyze_dataset(request: AnalyzeRequest):
    """Analyze COMPAS demo dataset with real Fairlearn + SHAP."""
    lr = model_state["model"]
    X = model_state["X"]
    y = model_state["y"]
    feature_cols = model_state["feature_cols"]
    raw_race = model_state["raw_race"]

    y_pred = lr.predict(X)

    # Real Fairlearn metrics
    fairness = compute_fairlearn_metrics(y, y_pred, raw_race.values)

    # Real SHAP values
    try:
        X_df = pd.DataFrame(X, columns=feature_cols)
        shap_results = compute_shap_values(lr, X_df, feature_cols)
        # Mark proxy features
        for sv in shap_results:
            sv["is_proxy"] = sv["feature"].lower() in ["race", "zipcode", "zip"]
    except Exception as e:
        print(f"[SHAP] Failed for COMPAS: {e}")
        # Fallback to coefficient-based importance
        coefs = np.abs(lr.coef_[0])
        max_c = coefs.max() if coefs.max() > 0 else 1.0
        shap_results = [
            {"feature": col.replace("_", " ").title(),
             "importance": round(float(coefs[i] / max_c), 4),
             "is_proxy": col.lower() in ["race", "zipcode"]}
            for i, col in enumerate(feature_cols)
        ]
        shap_results.sort(key=lambda x: x["importance"], reverse=True)
        shap_results = shap_results[:8]

    race_counts = raw_race.value_counts().to_dict()

    return {
        "dataset_name": request.dataset_name,
        "fairness_metrics": fairness,
        "shap_values": shap_results,
        "demographic_breakdown": race_counts,
        "verdict": "GUILTY" if any(v < 0.80 for k, v in fairness.items()
                                    if k in ("demographic_parity", "equal_opportunity", "disparate_impact")) else "NOT GUILTY",
        "summary": f"Fairlearn + SHAP analysis on {len(X)} samples across {len(feature_cols)} features.",
    }


@app.post("/mitigate")
async def mitigate_bias(request: MitigateRequest):
    """Mitigate COMPAS bias via reweighting."""
    lr_original = model_state["model"]
    X = model_state["X"]
    y = model_state["y"]
    sensitive = model_state["raw_race"].values

    y_pred_before = lr_original.predict(X)
    before_metrics = compute_fairlearn_metrics(y, y_pred_before, sensitive)

    sample_weights = compute_sample_weight(class_weight="balanced", y=sensitive)
    lr_mitigated = LogisticRegression(max_iter=1000, random_state=42)
    lr_mitigated.fit(X, y, sample_weight=sample_weights)

    y_pred_after = lr_mitigated.predict(X)
    after_metrics = compute_fairlearn_metrics(y, y_pred_after, sensitive)

    improvement = {}
    for key in ["demographic_parity", "equal_opportunity", "disparate_impact"]:
        bv = before_metrics.get(key, 0)
        av = after_metrics.get(key, 0)
        improvement[key] = round(((av - bv) / bv) * 100, 1) if bv > 0 else 0.0

    retrial_passed = all(after_metrics.get(k, 0) >= 0.80
                         for k in ("demographic_parity", "equal_opportunity", "disparate_impact"))

    return {
        "dataset_name": request.dataset_name,
        "technique": request.technique,
        "before": {k: before_metrics[k] for k in ("demographic_parity", "equal_opportunity", "disparate_impact")},
        "after": {k: after_metrics[k] for k in ("demographic_parity", "equal_opportunity", "disparate_impact")},
        "improvement": improvement,
        "retrial_passed": retrial_passed,
        "summary": f"Reweighting applied on {len(X)} samples.",
    }


@app.post("/simulate")
async def simulate_prediction(request: SimulateRequest):
    """Counterfactual simulation on COMPAS model."""
    if not model_state:
        return JSONResponse({"error": "Model not loaded"}, status_code=500)

    lr = model_state["model"]
    scaler = model_state["scaler"]
    feature_cols = model_state["feature_cols"]
    encoders = model_state["label_encoders"]
    df = model_state["df"]

    req_race = request.race
    if req_race == "African American":
        req_race = "African-American"

    base_row = {}
    for col in feature_cols:
        if col == "age":
            base_row[col] = request.age
        elif col == "priors_count":
            base_row[col] = request.prior_arrests
        elif col == "race":
            pass
        else:
            base_row[col] = df[col].mode()[0]

    def predict_for_race(race_val):
        row = base_row.copy()
        try:
            encoded_race = encoders["race"].transform([race_val])[0]
        except Exception:
            encoded_race = df["race"].mode()[0]
        row["race"] = encoded_race
        x_raw = np.array([[row[col] for col in feature_cols]])
        x_scaled = scaler.transform(x_raw)
        pred = lr.predict(x_scaled)[0]
        return "Denied" if pred == 1 else "Approved"

    original_prediction = predict_for_race(req_race)
    counterfactual_prediction = predict_for_race("Caucasian")

    return {
        "original_prediction": original_prediction,
        "counterfactual_prediction": counterfactual_prediction,
        "changed": original_prediction != counterfactual_prediction,
    }


# ═══════════════════════════════════════════════════════════════════════════════
#  NEW PIPELINE: Full Analysis (user model + dataset + training script)
# ═══════════════════════════════════════════════════════════════════════════════

@app.post("/full-analysis")
async def full_analysis(
    file: UploadFile = File(...),
    model_file: UploadFile = File(...),
    target_column: str = Form(...),
    sensitive_attributes: str = Form(...),
    training_script: UploadFile = File(None),
):
    """Accept dataset + model + optional training script. Run Fairlearn + SHAP + LLM analysis."""
    session_id = str(uuid.uuid4())[:8]
    workspace = WORKSPACE_DIR / session_id
    workspace.mkdir(parents=True, exist_ok=True)

    try:
        # ── Save uploaded files ──
        dataset_path = workspace / "dataset.csv"
        model_path = workspace / f"model{Path(model_file.filename).suffix}"
        dataset_path.write_bytes(await file.read())
        model_path.write_bytes(await model_file.read())

        script_content = None
        if training_script:
            script_path = workspace / "training_script.py"
            script_content = (await training_script.read()).decode("utf-8")
            script_path.write_text(script_content)

        # ── Parse inputs ──
        sensitive_list = [s.strip() for s in sensitive_attributes.split(",")]
        primary_sensitive = sensitive_list[0]

        # ── Load model ──
        model = load_model_file(str(model_path))
        model_type = type(model).__name__
        print(f"[SESSION {session_id}] Loaded model: {model_type}")

        # ── Load dataset ──
        df = pd.read_csv(str(dataset_path))
        if target_column not in df.columns:
            return JSONResponse(
                {"error": f"Target column '{target_column}' not found. Available: {list(df.columns)}"},
                status_code=400,
            )

        X, y, feature_cols, raw_sensitive, encoders = prepare_dataset(df, target_column, sensitive_list)

        if len(X) < 10:
            return JSONResponse({"error": "Dataset has fewer than 10 rows after cleaning."}, status_code=400)

        # ── Find primary sensitive column ──
        sensitive_col_key = next(
            (k for k in raw_sensitive if k.lower() == primary_sensitive.lower()), None
        )
        if not sensitive_col_key:
            return JSONResponse(
                {"error": f"Sensitive attribute '{primary_sensitive}' not found. Available: {list(df.columns)}"},
                status_code=400,
            )
        sensitive_values = raw_sensitive[sensitive_col_key]

        # ── Run predictions (smart feature matching) ──
        try:
            y_pred = model.predict(X.values)
        except Exception as pred_err:
            # Try to match model's expected features
            matched = False
            if hasattr(model, "feature_names_in_"):
                model_features = list(model.feature_names_in_)
                available = [f for f in model_features if f in X.columns]
                if len(available) == len(model_features):
                    X = X[available]
                    feature_cols = available
                    y_pred = model.predict(X.values)
                    matched = True
            
            if not matched and hasattr(model, "n_features_in_"):
                n_expected = model.n_features_in_
                if n_expected <= len(feature_cols):
                    # Try numeric-only columns matching expected count
                    X_numeric = X.select_dtypes(include=[np.number])
                    if len(X_numeric.columns) == n_expected:
                        X = X_numeric
                        feature_cols = list(X_numeric.columns)
                        y_pred = model.predict(X.values)
                        matched = True
                    elif len(X_numeric.columns) > n_expected:
                        # Take first n columns
                        X = X_numeric.iloc[:, :n_expected]
                        feature_cols = list(X.columns)
                        y_pred = model.predict(X.values)
                        matched = True

            if not matched:
                return JSONResponse(
                    {"error": f"Model prediction failed: {str(pred_err)}. Expected features: {getattr(model, 'feature_names_in_', 'unknown')}"},
                    status_code=400,
                )

        accuracy = round(accuracy_score(y, y_pred), 4)

        # ── Fairlearn metrics ──
        fairness = compute_fairlearn_metrics(y, y_pred, sensitive_values)

        # ── SHAP ──
        try:
            shap_results = compute_shap_values(model, X, feature_cols)
        except Exception as e:
            print(f"[SHAP] Failed: {e}")
            shap_results = [{"feature": col, "importance": 0, "raw_shap": 0} for col in feature_cols[:8]]

        # ── Proxy detection ──
        proxies = detect_proxy_features(df, sensitive_col_key, feature_cols)

        # Mark proxy features in SHAP results
        proxy_names = {p["feature"].lower() for p in proxies}
        for sv in shap_results:
            sv["is_proxy"] = sv["feature"].lower().replace(" ", "_") in proxy_names or \
                             sv["feature"].lower() in [s.lower() for s in sensitive_list]

        # ── LLM code analysis ──
        code_analysis = None
        current_key = get_gemini_key()
        if script_content and current_key:
            code_analysis = await analyze_code_with_llm(script_content, current_key)

        # ── Demographics ──
        demo_breakdown = pd.Series(sensitive_values).value_counts().to_dict()

        # ── Verdict ──
        verdict = "GUILTY" if any(
            fairness.get(k, 1.0) < 0.80
            for k in ("demographic_parity", "equal_opportunity", "disparate_impact")
        ) else "NOT GUILTY"

        bias_score = round((1 - (fairness["demographic_parity"] + fairness["equal_opportunity"] + fairness["disparate_impact"]) / 3) * 100)

        # ── Store session (memory + disk) ──
        session_data = {
            "workspace": str(workspace),
            "dataset_path": str(dataset_path),
            "model_path": str(model_path),
            "target_column": target_column,
            "sensitive_attributes": sensitive_list,
            "script_content": script_content,
            "model_type": model_type,
            "fairness_metrics": fairness,
            "shap_values": shap_results,
            "proxies": proxies,
            "code_analysis": code_analysis,
            "accuracy": accuracy,
            "verdict": verdict,
        }
        sessions[session_id] = session_data
        save_session(session_id, session_data)

        return {
            "session_id": session_id,
            "dataset_name": file.filename,
            "model_type": model_type,
            "rows": len(X),
            "features": len(feature_cols),
            "model_accuracy": accuracy,
            "target_column": target_column,
            "sensitive_attributes": sensitive_list,
            "fairness_metrics": fairness,
            "shap_values": shap_results,
            "proxy_features": proxies,
            "code_analysis": code_analysis,
            "demographic_breakdown": demo_breakdown,
            "verdict": verdict,
            "bias_score": bias_score,
            "script_content": script_content,
            "summary": f"Fairlearn + SHAP analysis on {len(X)} samples. Model type: {model_type}.",
        }

    except Exception as e:
        traceback.print_exc()
        return JSONResponse({"error": f"Analysis failed: {str(e)}"}, status_code=500)


# ═══════════════════════════════════════════════════════════════════════════════
#  NEW PIPELINE: Mitigate & Retrain
# ═══════════════════════════════════════════════════════════════════════════════

@app.post("/mitigate-and-retrain")
async def mitigate_and_retrain(request: RetrainRequest):
    """Use LLM to modify training script, retrain model, re-evaluate."""
    session = load_session(request.session_id)
    if not session:
        return JSONResponse(
            {"error": f"Session '{request.session_id}' not found. The session may have expired or the analysis was not completed. Please re-run the analysis from /full-analysis."},
            status_code=404,
        )

    # Verify critical files still exist on disk
    dataset_path = Path(session["dataset_path"])
    model_path = Path(session["model_path"])
    if not dataset_path.exists():
        return JSONResponse(
            {"error": f"Dataset file missing at '{dataset_path}'. The workspace may have been cleaned. Please re-upload and re-analyze."},
            status_code=404,
        )
    if not model_path.exists():
        return JSONResponse(
            {"error": f"Model file missing at '{model_path}'. The workspace may have been cleaned. Please re-upload and re-analyze."},
            status_code=404,
        )

    if not get_gemini_key():
        return JSONResponse(
            {"error": "GEMINI_API_KEY is not configured on the server. Automated retraining requires a Gemini API key in the environment."},
            status_code=500,
        )

    workspace = Path(session["workspace"])
    output_model_path = str(workspace / "mitigated_model.pkl").replace("\\", "/")

    # ── Determine script to use ──
    script_content = session.get("script_content")
    if not script_content:
        # Check if a training script file exists on disk (may have been uploaded separately)
        workspace = Path(session["workspace"])
        disk_script = workspace / "training_script.py"
        if disk_script.exists():
            script_content = disk_script.read_text()
            print(f"[SESSION {request.session_id}] Loaded training script from disk")
        else:
            # Auto-generate a training script using Gemini
            print(f"[SESSION {request.session_id}] No script uploaded, auto-generating for {session['model_type']}")
            try:
                auto_prompt = f"""Generate a complete, self-contained Python training script for the following:

- Model type: {session['model_type']}
- Dataset path: "{str(session['dataset_path']).replace('\\\\', '/')}"
- Target column: "{session['target_column']}"
- Sensitive attributes: {session['sensitive_attributes']}
- Save trained model to: "{output_model_path}" using joblib.dump()

The script must:
1. Load the CSV, handle missing values, encode categorical features
2. Split into train/test, train the model
3. Apply fairness constraints using sklearn sample_weight or post-processing
4. Save the model with joblib.dump()
5. Print a JSON line: {{"accuracy": 0.XX, "status": "success"}}
6. Be fully runnable with no external dependencies beyond sklearn, pandas, numpy, joblib

Return ONLY the Python code, no markdown fences or explanations."""
                script_content = await rotator.generate_content(auto_prompt)
                script_content = script_content.strip()
                if script_content.startswith("```"):
                    script_content = script_content.split("\n", 1)[1].rsplit("```", 1)[0].strip()
                print(f"[SESSION {request.session_id}] Auto-generated training script ({len(script_content)} chars)")
            except Exception as gen_err:
                print(f"[SESSION {request.session_id}] Gemini auto-gen failed: {gen_err}, using fallback")
                script_content = generate_fallback_training_script(
                    model_type=session["model_type"],
                    dataset_path=str(session["dataset_path"]).replace("\\", "/"),
                    target_column=session["target_column"],
                    sensitive_attrs=session["sensitive_attributes"],
                    output_model_path=output_model_path,
                )

    try:
        # ── Generate mitigated code — SINGLE LLM call, fast fallback ──
        import sys
        venv_python = sys.executable
        python_path = os.environ.get("PYTHON_PATH", venv_python)
        modified_script_path = workspace / "modified_training_script.py"

        modified_code = None
        retrain_success = False
        retrain_stdout = ""
        retrain_stderr = ""
        max_attempts = 2

        dataset_path_str = str(session["dataset_path"]).replace("\\", "/")
        target_col = session["target_column"]
        sens_attrs = session["sensitive_attributes"]

        bias_context = json.dumps({
            "fairness_metrics": session["fairness_metrics"],
            "proxy_features": session.get("proxies", []),
        }, indent=2)

        def _clean_code_block(text: str) -> str:
            text = text.strip()
            if text.startswith("```"):
                text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()
            return text

        for attempt in range(max_attempts):
            if attempt == 0:
                # ── ONE single LLM call to rewrite the script ──
                prompt = f"""Rewrite this Python training script to add bias mitigation.

ORIGINAL SCRIPT:
```python
{script_content}
```

BIAS ANALYSIS:
{bias_context}

REQUIREMENTS:
1. Read dataset from: "{dataset_path_str}"
2. Target column: "{target_col}"
3. Sensitive attributes: {sens_attrs}
4. Add sample reweighting with compute_sample_weight("balanced", y)
5. Add class_weight="balanced" to the model if supported
6. Remove proxy features correlated with sensitive attributes if any were detected
7. Save model to: "{output_model_path}" using joblib.dump()
8. Print JSON to stdout: {{"accuracy": 0.XX, "status": "success"}}
9. Fully self-contained, runnable with `python script.py`
10. Handle missing values, encode categoricals with LabelEncoder

Return ONLY the Python script, no markdown fences or explanations."""

                try:
                    print(f"[SESSION {request.session_id}] Single LLM call for mitigated script...")
                    modified_code = await rotator.generate_content(prompt, fan_out=2)
                    modified_code = _clean_code_block(modified_code)
                    print(f"[SESSION {request.session_id}] Got mitigated script ({len(modified_code)} chars)")
                except Exception as llm_err:
                    # Instant rule-based fallback — zero API calls
                    print(f"[SESSION {request.session_id}] LLM failed ({llm_err}), using rule-based fallback")
                    modified_code = generate_rule_based_fallback(
                        script_content=script_content,
                        dataset_path=dataset_path_str,
                        target_column=target_col,
                        sensitive_attrs=sens_attrs,
                        output_model_path=output_model_path,
                        proxy_features=session.get("proxies", []),
                    )
            else:
                # Retry: feed the error back
                print(f"[SESSION {request.session_id}] Retry — feeding error back to LLM")
                try:
                    fix_prompt = f"""Fix this Python script that failed with an error.

FAILED SCRIPT:
```python
{modified_code}
```

ERROR:
```
{retrain_stderr[-800:]}
```

Fix the error. Dataset: "{dataset_path_str}", target: "{target_col}", save to: "{output_model_path}".
Print JSON: {{"accuracy": 0.XX, "status": "success"}}. Return ONLY the fixed Python script."""

                    modified_code = await rotator.generate_content(fix_prompt, fan_out=2)
                    modified_code = _clean_code_block(modified_code)
                except Exception:
                    # If LLM fails on retry too, use rule-based
                    modified_code = generate_rule_based_fallback(
                        script_content=script_content,
                        dataset_path=dataset_path_str,
                        target_column=target_col,
                        sensitive_attrs=sens_attrs,
                        output_model_path=output_model_path,
                        proxy_features=session.get("proxies", []),
                    )

            # Write and execute
            modified_script_path.write_text(modified_code)
            print(f"[SESSION {request.session_id}] Attempt {attempt+1}/{max_attempts} - executing with: {python_path}")

            result = subprocess.run(
                [python_path, str(modified_script_path)],
                cwd=str(workspace),
                capture_output=True,
                text=True,
                timeout=120,
            )

            retrain_stdout = result.stdout
            retrain_stderr = result.stderr
            retrain_success = result.returncode == 0 and Path(output_model_path).exists()

            print(f"[SESSION {request.session_id}] Attempt {attempt+1} exit={result.returncode}, model_exists={Path(output_model_path).exists()}")
            if retrain_stderr:
                print(f"[SESSION {request.session_id}] STDERR (last 300): {retrain_stderr[-300:]}")

            if retrain_success:
                break

        if not retrain_success:
            return {
                "session_id": request.session_id,
                "retrain_success": False,
                "error": f"Retrain failed after {max_attempts} attempts (exit code {result.returncode})",
                "stdout": retrain_stdout[-2000:] if retrain_stdout else "",
                "stderr": retrain_stderr[-2000:] if retrain_stderr else "",
                "original_script": script_content,
                "modified_script": modified_code,
                "before": {k: float(session["fairness_metrics"][k]) for k in ("demographic_parity", "equal_opportunity", "disparate_impact")},
            }

        # ── Re-evaluate the retrained model ──
        new_model = load_model_file(output_model_path)
        df = pd.read_csv(session["dataset_path"])
        X, y, feature_cols, raw_sensitive, _ = prepare_dataset(
            df, session["target_column"], session["sensitive_attributes"]
        )

        sensitive_col_key = next(
            (k for k in raw_sensitive if k.lower() == session["sensitive_attributes"][0].lower()), None
        )
        sensitive_values = raw_sensitive[sensitive_col_key] if sensitive_col_key else np.zeros(len(y))

        # Smart feature matching (same logic as /full-analysis)
        try:
            y_pred_new = new_model.predict(X.values)
        except Exception:
            matched = False
            if hasattr(new_model, "feature_names_in_"):
                model_features = list(new_model.feature_names_in_)
                available = [f for f in model_features if f in X.columns]
                if len(available) == len(model_features):
                    X = X[available]
                    y_pred_new = new_model.predict(X.values)
                    matched = True

            if not matched and hasattr(new_model, "n_features_in_"):
                n_expected = new_model.n_features_in_
                X_numeric = X.select_dtypes(include=[np.number])
                if len(X_numeric.columns) >= n_expected:
                    X = X_numeric.iloc[:, :n_expected]
                    y_pred_new = new_model.predict(X.values)
                    matched = True

            if not matched:
                # Last resort: try numeric-only
                X_numeric = X.select_dtypes(include=[np.number])
                y_pred_new = new_model.predict(X_numeric.values)

        new_accuracy = round(accuracy_score(y, y_pred_new), 4)
        after_metrics = compute_fairlearn_metrics(y, y_pred_new, sensitive_values)

        # ── Compute improvement ──
        before = {k: float(session["fairness_metrics"][k]) for k in ("demographic_parity", "equal_opportunity", "disparate_impact")}
        after = {k: float(after_metrics[k]) for k in ("demographic_parity", "equal_opportunity", "disparate_impact")}
        improvement = {}
        for key in before:
            bv = before[key]
            av = after[key]
            improvement[key] = round(float(((av - bv) / bv) * 100), 1) if bv > 0 else 0.0

        retrial_passed = all(after.get(k, 0) >= 0.80 for k in after)

        # Update session (memory + disk)
        sessions[request.session_id]["mitigated_model_path"] = output_model_path
        sessions[request.session_id]["modified_script"] = modified_code
        sessions[request.session_id]["after_metrics"] = after_metrics
        save_session(request.session_id, sessions[request.session_id])

        return {
            "session_id": request.session_id,
            "retrain_success": True,
            "original_script": script_content,
            "modified_script": modified_code,
            "before": before,
            "after": after,
            "improvement": improvement,
            "original_accuracy": float(session["accuracy"]),
            "new_accuracy": float(new_accuracy),
            "retrial_passed": retrial_passed,
            "model_type": type(new_model).__name__,
            "summary": f"Retrained {type(new_model).__name__}. Accuracy: {session['accuracy']} -> {new_accuracy}.",
        }

    except subprocess.TimeoutExpired:
        return JSONResponse(
            {"error": "Retrain script timed out after 120 seconds. The dataset may be too large or the generated script may have an infinite loop. Try uploading a smaller dataset or provide your own training script."},
            status_code=500,
        )
    except Exception as e:
        traceback.print_exc()
        return JSONResponse(
            {"error": f"Mitigation failed: {str(e)}. Check the server logs for a full traceback."},
            status_code=500,
        )


# ─── Download Endpoints ──────────────────────────────────────────────────────

@app.get("/download/{session_id}/model")
async def download_model(session_id: str):
    session = load_session(session_id)
    if not session:
        return JSONResponse({"error": f"Session '{session_id}' not found. The analysis may have expired."}, status_code=404)
    model_path = session.get("mitigated_model_path")
    if not model_path or not Path(model_path).exists():
        return JSONResponse({"error": "No mitigated model found. Run 'Auto-Generate & Retrain' first."}, status_code=404)
    return FileResponse(model_path, filename="mitigated_model.pkl")


@app.get("/download/{session_id}/script")
async def download_script(session_id: str):
    session = load_session(session_id)
    if not session:
        return JSONResponse({"error": f"Session '{session_id}' not found. The analysis may have expired."}, status_code=404)
    if not session.get("modified_script"):
        return JSONResponse({"error": "No modified script found. Run 'Auto-Generate & Retrain' first."}, status_code=404)
    workspace = Path(session["workspace"])
    script_path = workspace / "modified_training_script.py"
    if script_path.exists():
        return FileResponse(str(script_path), filename="modified_training_script.py")
    return JSONResponse({"error": "Script file was deleted from disk. Please re-run the retrain step."}, status_code=404)


# ─── Legacy endpoint (keep for backwards compat) ─────────────────────────────

@app.post("/upload-and-analyze")
async def upload_and_analyze(
    file: UploadFile = File(...),
    target_column: str = Form(...),
    sensitive_attributes: str = Form(...),
):
    """Legacy: CSV-only upload. Trains logistic regression internally."""
    try:
        sensitive_list = [s.strip().lower() for s in sensitive_attributes.split(",")]
        primary_sensitive = sensitive_list[0]

        contents = await file.read()
        df = pd.read_csv(io.BytesIO(contents))

        if target_column not in df.columns:
            return JSONResponse(
                {"error": f"Target column '{target_column}' not found."},
                status_code=400,
            )

        X, y, feature_cols, raw_sensitive, encoders = prepare_dataset(df, target_column, sensitive_list)
        if len(X) < 10:
            return JSONResponse({"error": "Too few rows after cleaning."}, status_code=400)

        # Find sensitive column
        sensitive_col_key = next((k for k in raw_sensitive if k.lower() == primary_sensitive), None)

        # Train logistic regression
        from sklearn.preprocessing import StandardScaler as SS
        scaler = SS()
        X_scaled = scaler.fit_transform(X.values)
        lr = LogisticRegression(max_iter=1000, random_state=42)
        lr.fit(X_scaled, y)
        accuracy = accuracy_score(y, lr.predict(X_scaled))

        y_pred = lr.predict(X_scaled)
        sensitive_values = raw_sensitive.get(sensitive_col_key, np.zeros(len(y)))
        fairness = compute_fairlearn_metrics(y, y_pred, sensitive_values)

        # SHAP
        try:
            X_df = pd.DataFrame(X_scaled, columns=feature_cols)
            shap_results = compute_shap_values(lr, X_df, feature_cols)
        except Exception:
            coefs = np.abs(lr.coef_[0])
            max_c = coefs.max() if coefs.max() > 0 else 1.0
            shap_results = [
                {"feature": col.replace("_", " ").title(), "importance": round(float(coefs[i] / max_c), 4), "is_proxy": col.lower() in sensitive_list}
                for i, col in enumerate(feature_cols)
            ]
            shap_results.sort(key=lambda x: x["importance"], reverse=True)
            shap_results = shap_results[:8]

        for sv in shap_results:
            if "is_proxy" not in sv:
                sv["is_proxy"] = sv["feature"].lower().replace(" ", "_") in [s.lower() for s in sensitive_list]

        demo_breakdown = pd.Series(sensitive_values).value_counts().to_dict() if sensitive_col_key else {}

        session_id = str(uuid.uuid4())[:8]
        workspace = WORKSPACE_DIR / session_id
        workspace.mkdir(parents=True, exist_ok=True)

        dataset_path = workspace / "dataset.csv"
        dataset_path.write_bytes(contents)

        model_path = workspace / "model.pkl"
        joblib.dump(lr, model_path)

        session_data = {
            "workspace": str(workspace),
            "dataset_path": str(dataset_path),
            "model_path": str(model_path),
            "target_column": target_column,
            "sensitive_attributes": sensitive_list,
            "script_content": None,
            "model_type": "LogisticRegression",
            "fairness_metrics": fairness,
            "shap_values": shap_results,
            "proxies": [],
            "code_analysis": None,
            "accuracy": accuracy,
            "verdict": "GUILTY" if any(fairness.get(k, 1) < 0.80 for k in ("demographic_parity", "equal_opportunity", "disparate_impact")) else "NOT GUILTY",
        }
        sessions[session_id] = session_data
        save_session(session_id, session_data)

        return {
            "session_id": session_id,
            "dataset_name": file.filename,
            "rows": len(X),
            "features": len(feature_cols),
            "model_accuracy": round(accuracy, 4),
            "target_column": target_column,
            "sensitive_attributes": sensitive_list,
            "fairness_metrics": fairness,
            "shap_values": shap_results,
            "demographic_breakdown": demo_breakdown,
            "verdict": session_data["verdict"],
            "summary": f"Analysis on {len(X)} samples across {len(feature_cols)} features.",
        }

    except Exception as e:
        traceback.print_exc()
        return JSONResponse({"error": f"Analysis failed: {str(e)}"}, status_code=500)
